name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
      with:
        registry: harbor.service.com:32429
        username: ${{ secrets.REGISTRY_USERBANE  }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag harbor.service.com:32429/library/go-file-generator:$(date +%s)
    - name: Push the Docker image
      run: 
        docker push harbor.service.com:32429/library/go-file-generator:$(date +%s) 
        
